services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=postgres
      - DB_PORT=5432
    stdin_open: true
    tty: true

volumes: 
  db:
